spring:
  application:
    name: task-service
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/ordinatus
    username: ordinatus
    password: ordinatus
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
logging:
  level:
    org.hibernate.SQL: debug
